services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: $DATABASE_URL

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  python:
    build: .