services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - db-to-python
    volumes:
      - postgres_data:/var/lib/postgresql/data

  python:
    build:
      context: .
      dockerfile: Dockerfile
    command: python run.py
    env_file:
      - .env
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    networks:
      - db-to-python

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db-to-python

networks:
  db-to-python:
    driver: bridge

volumes:
  postgres_data:
